
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author melam
 */
public class ViewCars extends javax.swing.JFrame {
   
    /**
     * Creates new form ViewCars
     */
    public ViewCars() {
        initComponents();
        jlInstall.setVisible(false);
        jlSell.setVisible(false);
        jlInterest.setVisible(false);
        jlDeposit.setVisible(false);
        jlBalloon.setVisible(false);
        jlInstallNum.setVisible(false);
        jlTotal.setVisible(false);
        jlImage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbChoose = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlSell = new javax.swing.JLabel();
        jlInstall = new javax.swing.JLabel();
        jlInterest = new javax.swing.JLabel();
        jlDeposit = new javax.swing.JLabel();
        jlBalloon = new javax.swing.JLabel();
        jlInstallNum = new javax.swing.JLabel();
        jlTotal = new javax.swing.JLabel();
        jbBack = new javax.swing.JButton();
        jlImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Please choose your preferred car");

        jcbChoose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Polo", "Polo Vivo", "T-Cross", "T-Roc" }));
        jcbChoose.setSelectedIndex(-1);
        jcbChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbChooseActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(265, 230));
        jPanel1.setMinimumSize(new java.awt.Dimension(265, 230));

        jLabel2.setText("Installment");

        jLabel3.setText("Selling price");

        jLabel4.setText("Interest rate");

        jl.setText("Deposit");

        jLabel6.setText("Balloon payment");

        jLabel7.setText("Installments");

        jLabel8.setText("Total cost of credit");

        jlSell.setText("null");

        jlInstall.setText("null");

        jlInterest.setText("null");

        jlDeposit.setText("null");

        jlBalloon.setText("null");

        jlInstallNum.setText("null");

        jlTotal.setText("null");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jl)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlBalloon, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jlInstallNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlInterest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlInstall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlSell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlInstall))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlSell))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlInterest)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDeposit)
                    .addComponent(jl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBalloon)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlInstallNum)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTotal)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        jbBack.setText("Back");
        jbBack.setToolTipText("");
        jbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBackActionPerformed(evt);
            }
        });

        jlImage.setText("Image");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jcbChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(582, Short.MAX_VALUE)
                        .addComponent(jbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jlImage, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jcbChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlImage)
                        .addGap(74, 74, 74)))
                .addComponent(jbBack)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   
    
    private void jcbChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbChooseActionPerformed
           jlInstall.setVisible(true);
           jlSell.setVisible(true);
           jlInterest.setVisible(true);
           jlDeposit.setVisible(true);
           jlBalloon.setVisible(true);
           jlInstallNum.setVisible(true);
           jlTotal.setVisible(true);
           jlImage.setVisible(true);
           
        if(jcbChoose.getSelectedItem().equals("Polo")){
           
           jlImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\melam\\Desktop\\JD522 FA2\\Polos\\poloTsi.png"));
           Polo polo = new Polo();
           jlInstall.setText("R" + Float.toString((float)(polo.getInstallAmt())));
           jlSell.setText("R" + Float.toString((float)(polo.getSellPrice())));
           jlInterest.setText(Double.toString((polo.getIntRate())) + "%");
           jlDeposit.setText(Double.toString((polo.getDeposit())) + "%");
           jlBalloon.setText("R" + Float.toString((float)(polo.getBaloon())));
           jlInstallNum.setText(Integer.toString((polo.getInstallNum())));
           jlTotal.setText("R" + Float.toString((float)(polo.Calculate())));
           
        }
        else if(jcbChoose.getSelectedItem().equals("Polo Vivo")){
           jlImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\melam\\Desktop\\JD522 FA2\\Polos\\comfortline.png"));
           PoloVivo polovivo = new PoloVivo();
           jlInstall.setText("R" + Float.toString((float)(polovivo.getInstallAmt())));
           jlSell.setText("R" + Float.toString((float)(polovivo.getSellPrice())));
           jlInterest.setText(Double.toString((polovivo.getIntRate())) + "%");
           jlDeposit.setText(Double.toString((polovivo.getDeposit())) + "%");
           jlBalloon.setText("R" + Float.toString((float)(polovivo.getBaloon())));
           jlInstallNum.setText(Integer.toString((polovivo.getInstallNum())));
           jlTotal.setText("R" + Float.toString((float)(polovivo.Calculate())));
            
        }
        else if(jcbChoose.getSelectedItem().equals("T-Cross")){
           jlImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\melam\\Desktop\\JD522 FA2\\Polos\\tcross.png"));
           TCross tcross = new TCross();
           jlInstall.setText("R" + Float.toString((float)(tcross.getInstallAmt())));
           jlSell.setText("R" + Float.toString((float)(tcross.getSellPrice())));
           jlInterest.setText(Double.toString((tcross.getIntRate())) + "%");
           jlDeposit.setText(Double.toString((tcross.getDeposit())) + "%");
           jlBalloon.setText("R" + Float.toString((float)(tcross.getBaloon())));
           jlInstallNum.setText(Integer.toString((tcross.getInstallNum())));
           jlTotal.setText("R" + Float.toString((float)(tcross.Calculate())));
            
        }
        else if(jcbChoose.getSelectedItem().equals("T-Roc")){
           jlImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\melam\\Desktop\\JD522 FA2\\Polos\\troc.png"));
           TRoc troc = new TRoc();
           jlInstall.setText("R" + Float.toString(((float)troc.getInstallAmt())));
           jlSell.setText("R" + Float.toString((float)(troc.getSellPrice())));
           jlInterest.setText(Double.toString((troc.getIntRate())) + "%");
           jlDeposit.setText(Double.toString((troc.getDeposit())) + "%");
           jlBalloon.setText("R" + Double.toString((float)(troc.getBaloon())));
           jlInstallNum.setText(Integer.toString((troc.getInstallNum())));
           jlTotal.setText("R" + Float.toString(((float)troc.Calculate())));
            
        }
        
    }//GEN-LAST:event_jcbChooseActionPerformed

    private void jbBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBackActionPerformed
        this.setVisible(false);
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbBack;
    private javax.swing.JComboBox<String> jcbChoose;
    private javax.swing.JLabel jl;
    private javax.swing.JLabel jlBalloon;
    private javax.swing.JLabel jlDeposit;
    private javax.swing.JLabel jlImage;
    private javax.swing.JLabel jlInstall;
    private javax.swing.JLabel jlInstallNum;
    private javax.swing.JLabel jlInterest;
    private javax.swing.JLabel jlSell;
    private javax.swing.JLabel jlTotal;
    // End of variables declaration//GEN-END:variables
}
